[package]
name = "libzephir"
version = "0.1.0"
authors = ["Alessandro Chitolina <alekitto@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
darling = "0.12"
log = "0.4"
mouscache = "0.5"
num-traits = "0.2"
pcre2 = "0.2"
redis = "0.10"
regex = "1"
serde_json = "1.0"
uluru = "1.1.1"

[dependencies.sqlx]
version = "0.5.1"
features = [ "all-databases", "macros", "json", "offline", "runtime-async-std-native-tls" ]
